# numpy 教學

In [ ]:
import numpy as np #之後可直接調用

In [ ]:
from numpy import random #之後要用 random.XXX 來調用

In [2]:
#輸入np array
import numpy as np
data = np.array([9,2,3,4,10,6,7,8,1,5])
data.dtype

dtype('int32')

In [4]:
#輸入計算出array維度與元素數量
import numpy as np
data = np.array([9,2,3,4,10,6,7,8,1,5])
print('維度',data.ndim)
print('元素數量',data.size)

維度 1
元素數量 10


In [5]:
import numpy as np
data = np.array([9,2,3,4,10,6,7,8,1,5])
print('data*2',data*2)
print('乘法運算：',np.array([1,2,3,4,5,6,7,8,9,9]*np.array([10,9,8,7,6,5,4,3,2,1])))
print('連乘：',data**2)
print('除法：',np.array([1,2,3,4,5,6,7,8,9,9]/np.array([10,9,8,7,6,5,4,3,2,1])))

data*2 [18  4  6  8 20 12 14 16  2 10]
乘法運算： [10 18 24 28 30 30 28 24 18  9]
連乘： [ 81   4   9  16 100  36  49  64   1  25]
除法： [0.1        0.22222222 0.375      0.57142857 0.83333333 1.2
 1.75       2.66666667 4.5        9.        ]


In [12]:
#array值排序
import numpy as np
data = np.array([9,2,3,4,10,6,7,8,1,5])
print(data)
data.sort()
print(data)
data[::-1].sort()
print(data)

[ 9  2  3  4 10  6  7  8  1  5]
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [14]:
#array最小值、最大值、總和、累積和、累積比例
import numpy as np
data = np.array([9,2,3,4,10,6,7,8,1,5])
print('最小值',data.min())
print('最大值',data.max())
print('total',data.sum())
print('累積和',data.cumsum())
print('累積比例',data.cumsum()/data.sum())

最小值 1
最大值 10
total 55
累積和 [ 9 11 14 18 28 34 41 49 50 55]
累積比例 [0.16363636 0.2        0.25454545 0.32727273 0.50909091 0.61818182
 0.74545455 0.89090909 0.90909091 1.        ]


In [18]:
#顯示到小數點後第三位
%precision 3

'%.3f'

In [19]:
#產生亂數
from numpy import random
random.seed(0)
rnd_data = random.randn(10)
print(rnd_data)

[ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]


In [17]:
data = np.array([9,2,3,4,10,6,7,8,1,5])

# 隨機取出
# 取出10個(允許重複，放回抽樣)
print(random.choice(data,10))
#  取出10個(不允許重複，不放回抽樣)
print(random.choice(data,10,replace = False))

[ 7  8  8  1  2  6  5  1  5 10]
[10  2  7  8  3  1  6  5  9  4]


In [20]:
#產生矩陣
import numpy as np
array1 = np.arange(9)
print(array1)
array2 = array1.reshape(3,3)
print(array1)
print(array2)
print('第一列',array2[0,:])
print('第一行',array2[:,0])

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
第一列 [0 1 2]
第一行 [0 3 6]


In [23]:
#矩陣運算
import numpy as np
array1 = np.arange(9).reshape(3,3)
array2 = np.arange(9,18).reshape(3,3)
print(array1)
print(array2)
print('乘法:',np.dot(array1,array2))
print('元素直接乘:',(array1*array2))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
乘法: [[ 42  45  48]
 [150 162 174]
 [258 279 300]]
元素直接乘: [[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [28]:
#製作元素為0或1的矩陣

print(np.zeros((2,3),dtype = np.int64))
print(np.ones((2,3),dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


# 練習

1. 使用np.array來製作1到50的陣列，計算從1到50的自然數總和，並顯示最後的計算成果
2. 依標準常態生成10個亂數，並製作陣列，求得其中的最小值、最大值、總和 (種子為0)
3. 製作所有元素均為3的5列5行矩陣，計算該矩陣的平 方


In [34]:
data = np.array(range(1,51))
print(data.sum())

1275


In [37]:
from numpy import random
random.seed(0)
rnd_data = random.randn(10)
data = np.array(rnd_data)
print('min:',data.min())
print('max:',data.max())
print('sum:',data.sum())

min: -0.977277879876411
max: 2.240893199201458
sum: 7.380231707288347


In [45]:
array = np.zeros((5,5),dtype = np.int64)
array[:,:] = 3
print(array)
np.dot(array,array)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]], dtype=int64)

In [51]:
random.seed(1)
rnd_data = random.randn(4*4).reshape(4,4)
print(rnd_data)
random.seed(2)
array2 = np.zeros((4,4),dtype = np.int64)
rnd_data2 = random.randn(4*4).reshape(4,4)
print(rnd_data2)
print(rnd_data*rnd_data2)
print(np.dot(rnd_data,rnd_data2))

[[ 1.624 -0.612 -0.528 -1.073]
 [ 0.865 -2.302  1.745 -0.761]
 [ 0.319 -0.249  1.462 -2.06 ]
 [-0.322 -0.384  1.134 -1.1  ]]
[[-0.417 -0.056 -2.136  1.64 ]
 [-1.793 -0.842  0.503 -1.245]
 [-1.058 -0.909  0.551  2.292]
 [ 0.042 -1.118  0.539 -0.596]]
[[-0.677  0.034  1.128 -1.76 ]
 [-1.552  1.937  0.877  0.948]
 [-0.338  0.227  0.806 -4.722]
 [-0.013  0.429  0.611  0.656]]
[[ 0.934  2.103 -4.647  2.855]
 [ 1.889  1.154 -2.454  8.739]
 [-1.318  1.166 -1.111  5.413]
 [-0.422  0.54   0.528  3.204]]
